# Generated by Django 3.1.5 on 2021-02-23 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=54, null=True)),
                ('patient_id', models.CharField(max_length=14)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('height', models.CharField(max_length=5, null=True)),
                ('blood_type', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=10)),
                ('bmi', models.CharField(max_length=15, null=True)),
                ('allergies', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('support_contact', models.CharField(max_length=100)),
                ('pregnant', models.BooleanField(null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patient_registry.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('personnel_id', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_patient_record', 'Can view Patient Record'),),
            },
        ),
    ]
